INSERT INTO APPLICATION (ID,APPNAME,ACCESS,SALT) VALUES ('MYID123','DOCTORAPP1','GHGI5KFJGFKD5','DJFDJFD');
INSERT INTO APPLICATION (ID,APPNAME,ACCESS,SALT) VALUES ('MYID124','DOCTORAPP2','GHGIDJFDFFKD5','TRTRTER');
INSERT INTO APPLICATION (ID,APPNAME,ACCESS,SALT) VALUES ('MYID125','DOCTORAPP3','KFJF5KFJGFKD5','BVBCVBB');
INSERT INTO APPLICATION (ID,APPNAME,ACCESS,SALT) VALUES ('MYID126','DOCTORAPP4','GHGSDFSSFFKD5','IOIOIOR');