INSERT INTO AUTHENTICATION (USERNAME,PASSWORD,USERID,APPID) VALUES ('USER1','PASSWORD','USERID1','MYAPP1');
INSERT INTO AUTHENTICATION (USERNAME,PASSWORD,USERID,APPID) VALUES ('USER2','PASSWORD','USERID2','MYAPP1');
INSERT INTO AUTHENTICATION (USERNAME,PASSWORD,USERID,APPID) VALUES ('USER3','PASSWORD','USERID3','MYAPP1');
INSERT INTO AUTHENTICATION (USERNAME,PASSWORD,USERID,APPID) VALUES ('USER4','PASSWORD','USERID4','MYAPP1');
INSERT INTO AUTHENTICATION (USERNAME,PASSWORD,USERID,APPID) VALUES ('USER5','PASSWORD','USERID5','MYAPP1');

INSERT INTO AUTHENTICATION (USERNAME,PASSWORD,USERID,APPID) VALUES ('USER6','PASSWORD','USERID6','MYAPP2');
INSERT INTO AUTHENTICATION (USERNAME,PASSWORD,USERID,APPID) VALUES ('USER7','PASSWORD','USERID7','MYAPP2');
INSERT INTO AUTHENTICATION (USERNAME,PASSWORD,USERID,APPID,TOKEN) VALUES ('USER8','PASSWORD','USERID8','MYAPP2','HNDHDN655HD5DH');
