INSERT INTO DOCTOR ( ID,DRNAME,DEGREE ) VALUES ('5236','JANENNA', 'DEGREE');
INSERT INTO DOCTOR ( ID,DRNAME,DEGREE ) VALUES ('FN125','SHRI RAM', 'MBBS');
INSERT INTO DOCTOR ( ID,DRNAME,DEGREE ) VALUES ('56989','JITENDRA', 'MD');
INSERT INTO DOCTOR ( ID,DRNAME,DEGREE ) VALUES ('56986','JIT', 'MD');